### ISSUE TITLE
Update website background

### ISSUE THREAD

**Issue by raniel182** [fluany/fluany#20]

**Comment by raniel182** [comment]
![bg_fluany_site](https://user-images.githubusercontent.com/26752216/33223490-1272d242-d147-11e7-82d5-d46d28d6031b.png)

![image](https://user-images.githubusercontent.com/26752216/33223494-195bdc52-d147-11e7-809c-cb12668efdd9.png)

**Comment by victorvoid** [comment]
developed in 2 commits:
- [48265a60132a9a5cb3ad14b368115d97e2980182](https://github.com/fluany/fluany/commit/48265a60132a9a5cb3ad14b368115d97e2980182)
- [48265a60132a9a5cb3ad14b368115d97e2980182](https://github.com/fluany/fluany/commit/48265a60132a9a5cb3ad14b368115d97e2980182)
